FROM node:alpine3.18

# Declare build time environment variable
ARG NODE_ENV
ARG MONGO_DB_PASSWORD
ARG REMAINDER_EMAIL_USERNAME
ARG REMAINDER_EMAIL_PASSWORD

# Set the environment variable
ENV NODE_ENV=$NODE_ENV
ENV MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
ENV REMAINDER_EMAIL_USERNAME=$REMAINDER_EMAIL_USERNAME
ENV REMAINDER_EMAIL_PASSWORD=$REMAINDER_EMAIL_PASSWORD

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 4000
CMD ["npm", "run", "start"]