name: Deploy Server Side Node Application

on:
  push:
    branches:
      - mern-ec2-docker
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t stevesiddu49/todo-server .
          --build-arg NODE_ENV='production'
      - name: Publish image to dockerhub
        run: docker push stevesiddu49/todo-server:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Current working directory
        run: pwd
      - name: Active running jobs with active-runner
        run: ps aux | grep actions-runner
      - name: Pull image from dockerhub
        run: docker pull stevesiddu49/todo-server:latest
      - name: Delete old Container
        run: docker rm -f todo-server-container
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name todo-server-container -e MONGO_DB_PASSWORD='${{ secrets.MONGO_DB_PASSWORD }}' stevesiddu49/todo-server